# Generated by Django 5.0.1 on 2024-12-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_questionpaper_year_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='branch',
            field=models.CharField(blank=True, choices=[('CSE', 'Computer Science Engineering'), ('IT', 'Information Technology'), ('Allied', 'Allied Branches')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='file',
            field=models.FileField(upload_to='papers/'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='year_of_study',
            field=models.CharField(choices=[('1st', '1st Year'), ('2nd', '2nd Year'), ('3rd', '3rd Year'), ('4th', '4th Year')], max_length=10),
        ),
    ]
