# Generated by Django 5.0.1 on 2024-12-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_questionpaper_branch_alter_questionpaper_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionpaper',
            old_name='year',
            new_name='paper_year',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='uploaded_at',
        ),
    ]
