# Generated by Django 5.0.1 on 2024-12-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_rename_year_questionpaper_paper_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
